controllers/TiketingController.php
<?php

namespace app\controllers;

use Yii;
use app\models\TiketBooking;
use yii\data\ActiveDataProvider;
use yii\db\Expression;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TiketingController implements the CRUD actions for TiketBooking model.
 */
class TiketingController extends Controller
{
    public $layout = 'main-adm';
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'create','artikel','createdet','updatedet','getdataartikel','getdatadetartikel'],
                'rules' => [
                    [
                        'actions' => ['index', 'create','view','delete','update','artikel','createdet','updatedet','getdataartikel','getdatadetartikel'],
                        'allow' => true,
                        //'roles' => ['@'],
                        'matchCallback'=>function(){
                            return (
                                Yii::$app->user->identity['role'] == '1'
                            );
                        }
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all TiketBooking models.
     * @return mixed
     */
    public function actionIndex()
    {
//        $this->layout = "@app/views/layouts/main-adm";
        $dataProvider = new ActiveDataProvider([
            'query' => (new Query())
                ->select([
                    'tiket_booking.*',
                    'member.fullname',
                    'member.email',
                    'member.phone',
                    'member.tgl_lahir',
                    'member.tempat_lahir',
                    'member.domisili',
                    'artdata.judul',
                    'artdata.sesi',
                    'artdata.jam_tayang',
                    'artdata.ket',
                ])
                ->from('tiket_booking')
                ->join('join','member','member.id=tiket_booking.id_member')
                ->join('join','(select artikel.judul, artikel_detail.id, artikel_detail.ket, artikel_detail.jml_tiket, artikel_detail.jml_terjual, artikel_detail.harga, artikel_detail.sesi, artikel_detail.jam_tayang from artikel_detail join artikel on artikel.id = artikel_detail.id_artikel) artdata', 'artdata.id = tiket_booking.id_artikel_detail')
            ->orderBy(['tiket_booking.created_by'=>SORT_DESC])
            //TiketBooking::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single TiketBooking model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new TiketBooking model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new TiketBooking();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing TiketBooking model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing TiketBooking model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the TiketBooking model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return TiketBooking the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = TiketBooking::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    function actionProses(){
        if($_POST){
            $req = Yii::$app->request->post();
            $pros = $req['reqproses'];
            $idtiket = $req['idtiket'];
            $findtiket = (new Query())
                ->select(['tiket_booking.*','member.fullname','member.email','member.phone','member.tgl_lahir','member.tempat_lahir','member.domisili'])
                ->from('tiket_booking')
                ->join('join','member','member.id = tiket_booking.id_member')
                ->where(['tiket_booking.id'=>$idtiket])->one();
//            $findtiket = TiketBooking::find()->where(['id'=>$idtiket])->one();
            if(!empty($findtiket)) {
                $username = Yii::$app->user->identity->username;
                if ($pros == 'cancel') {
                    Yii::$app->db->createCommand()->update('tiket_booking',array('status'=>'cancel','updated_by'=>date("Y-m-d H:i:s"),'proses_by'=>$username),array('no_order'=>$findtiket['no_order'],'id'=>$findtiket['id']))->execute();
                    $this->kirimEmail($findtiket['email'], $findtiket['fullname'], number_format($findtiket['total_harga'], 0, '', '.'),$findtiket['no_order']);
                    echo json_encode(array('rc'=>200,'msg'=>'Sudah di proses dan sistem telah mengirim E-Mail'));
                    exit;
                }
                if ($pros == 'approve') {
                    Yii::$app->db->createCommand()->update('tiket_booking',array('status'=>'konfirmasi','updated_by'=>date("Y-m-d H:i:s"),'proses_by'=>$username),array('no_order'=>$findtiket['no_order'],'id'=>$findtiket['id']))->execute();
                    $this->kirimEmail($findtiket['email'], $findtiket['fullname'], number_format($findtiket['total_harga'], 0, '', '.'),$findtiket['no_order']);
                    echo json_encode(array('rc'=>200,'msg'=>'Sudah di proses dan sistem telah mengirim E-Mail'));
                    exit;}
            }
            echo json_encode(array('rc'=>400,'msg'=>'Gagal di proses'));
            exit;
        }
    }
    function kirimEmail($to, $nama, $jmlduit,$order)
    {
//        $message_html = '<p>Hallo <b>{{nama}}</b>,</p>
//<p>Barusan anda melakukan Booking, silakan transfer <b>{{jml_duit}}</b> dan kirim kan bukti agar kami segera proses.</p>';
//        $message_html = str_replace(array('{{nama}}', '{{jml_duit}}'), array($nama, $jmlduit), $message_html);
        $tiketbook = (new Query())
            ->select([new Expression('sum(jml_tiket * harga) total_tagihan'),'status','no_order','diskon','total_harga'])
            ->from('tiket_booking')->where(['no_order'=>$order])->one();
        $data['tiket']=$tiketbook;
        $this->layout=false;
        $message_html = $this->render('@app/views/info/index',$data);
        $a = Yii::$app->mailer->compose()
//            ->setFrom('noreply@sensyari-indonesia.com')
            ->setFrom('sensyari@sensyari-indonesia.com')
            ->setTo($to)
            ->setSubject('[Informasi Order]')
//                ->setTextBody('Plain text content')
            ->setHtmlBody($message_html)
            ->send();
    }
}

views/tiketing/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\TiketBooking */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tiket-booking-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'id_member')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'id_artikel_detail')->textInput() ?>

    <?= $form->field($model, 'jml_tiket')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'status')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'created_by')->textInput() ?>

    <?= $form->field($model, 'updated_by')->textInput() ?>

    <?= $form->field($model, 'jenis')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'harga')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'no_order')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/tiketing/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\TiketBooking */

$this->title = 'Create Tiket Booking';
$this->params['breadcrumbs'][] = ['label' => 'Tiket Bookings', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tiket-booking-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/tiketing/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Tiket Bookings';
?>

<script>
    if (location.protocol != 'https:') { location.href = 'https:' + window.location.href.substring(window.location.protocol.length); }
</script>
<div class="tiket-booking-index">
    <div class="card">
        <div class="card-header">
            <h3><?= Html::encode($this->title) ?></h3>
        </div>
        <div class="card-body table-responsive">

            <?php $data = $dataProvider->query->all();
            ?>
            <table class="table table-striped" id="tiketsdt">
                <thead>
                <tr>
                    <th>Member</th>
                    <th>Telp</th>
                    <th>Email</th>
                    <th>Domisili</th>
                    <th>No. Order</th>
                    <th>Produk</th>
                    <th>Sesi</th>
                    <th>Seat</th>
                    <th>Jumlah Tiket</th>
                    <th>Harga Tiket</th>
                    <th>Total Harga</th>
                    <th>Tgl Order</th>
                    <th>Tgl Proses</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($data as $r): ?>
                    <tr>
                        <td>
                            <?php echo $r['fullname'] ?>
                        </td>
                        <td><?php echo $r['phone'] ?></td>
                        <td><?php echo $r['email'] ?></td>
                        <td><?php echo $r['domisili'] ?></td>
                        <td><?php echo $r['no_order'] ?></td>
                        <td>
                            <?php echo $r['judul'] ?><br>
                        </td>
                        <td><?php echo $r['sesi'] ?> <?php echo $r['jam_tayang'] ?></td>
                        <td><?php echo $r['ket'] ?></td>
                        <td><?php echo $r['jml_tiket'] ?></td>
                        <td><?php echo $r['harga'] ?></td>
                        <td><?php echo $r['total_harga'] ?></td>
                        <td><?php echo $r['created_by'] ?></td>
                        <td><?php echo $r['updated_by'] ?></td>
                        <td><label class="btn <?php echo $r['status'] == 'waiting' ? "btn-outline-success" :"btn-outline-danger" ?>"><?php echo $r['status'] ?></label></td>
                        <td>
                            <?php if($r['status'] == 'waiting'): ?>
                                <button data-url="<?php echo str_replace('http://', 'https://', \yii\helpers\Url::to(['/tiketing/proses'], true)) ?>"
                                        data-id="<?php echo $r['id'] ?>" class="btnappr btn btn-sm btn-outline-primary"
                                        data-valuecsrf="<?=Yii::$app->request->csrfToken?>"
                                        title="Approve tiket"><span class="fa fa-check"></span></button>
                                <button data-url="<?php echo str_replace('http://', 'https://', \yii\helpers\Url::to(['/tiketing/proses'], true)) ?>"
                                        data-id="<?php echo $r['id'] ?>" class="btncancel btn btn-sm btn-outline-primary"
                                        data-valuecsrf="<?=Yii::$app->request->csrfToken?>"
                                        title="Cancel Tiket" class="btncancel btn btn-sm btn-outline-danger"><span class="fa fa-trash"></span>
                                </button>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>


</div>
<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet">
<link href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.dataTables.min.css" rel="stylesheet">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
<script>
    $(document).ready( function () {
        $("#tiketsdt").DataTable({
            dom: 'Bfrtip',
            buttons: [
                // 'copyHtml5',
                'excelHtml5',
                // 'csvHtml5',
                // 'pdfHtml5'
            ]
        });
    });
    jQuery(document).on('click','.btnappr', function () {
        var iddt = $(this).attr('data-id');
        var urls = $(this).attr('data-url');
        var valuecsrf = $(this).attr('data-valuecsrf');
        swal({
            title: "Are you sure?",
            text: "Anda akan Approve orderan ini!",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
            .then((willDelete) => {
                if (willDelete) {
                    $.ajax({
                        url: urls,
                        method: "POST",
                        data: {idtiket: iddt, _csrf:valuecsrf, reqproses:'approve'},
                        dataType: "json",
                        beforeSend:function(){
                            swal("Sedang Diproses");
                        },
                        success:function (msg) {
                            if(msg.rc == 200){
                                swal(msg.msg);
                            }else{ swal(msg.msg);}
                            document.location.reload(true);
                        }
                    });
                }
            });
    });
    jQuery(document).on('click','.btncancel', function () {
        var iddt = $(this).attr('data-id');
        var urls = $(this).attr('data-url');
        var valuecsrf = $(this).attr('data-valuecsrf');
        swal({
            title: "Are you sure?",
            text: "Anda akan membatalkan orderan!",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
            .then((willDelete) => {
                if (willDelete) {
                    $.ajax({
                        url: urls,
                        method: "POST",
                        data: {idtiket: iddt, _csrf:valuecsrf, reqproses:'cancel'},
                        dataType: "json",
                        beforeSend:function(){
                            swal("Sedang Diproses");
                        },
                        success:function (msg) {
                            if(msg.rc == 200){
                                swal(msg.msg);
                            }else{ swal(msg.msg);}
                            document.location.reload(true);
                        }
                    });
                }
            });
    })
</script>

views/tiketing/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\TiketBooking */

$this->title = 'Update Tiket Booking: {nameAttribute}';
$this->params['breadcrumbs'][] = ['label' => 'Tiket Bookings', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="tiket-booking-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/tiketing/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\TiketBooking */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Tiket Bookings', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tiket-booking-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'id_member',
            'id_artikel_detail',
            'jml_tiket',
            'status',
            'created_by',
            'updated_by',
            'jenis',
            'harga',
            'no_order',
            'approve_by',
        ],
    ]) ?>

</div>