controllers/AdmController.php
<?php

namespace app\controllers;

use Yii;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Artikel;
use app\models\ArtikelDetail;

class AdmController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public $layout = 'main-adm';
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'create','artikel','createdet','updatedet','getdataartikel','getdatadetartikel'],
                'rules' => [
                    [
                        'actions' => ['index', 'create','view','delete','update','artikel','createdet','updatedet','getdataartikel','getdatadetartikel'],
                        'allow' => true,
                        //'roles' => ['@'],
                        'matchCallback'=>function(){
                            return (
                                Yii::$app->user->identity['role'] == '1'
                            );
                        }
                    ],
                ],
            ],
        ];
//        return [
//            'access' => [
//                'class' => AccessControl::className(),
//                'only' => ['logout'],
//                'rules' => [
//                    [
//                        'actions' => ['logout'],
//                        'allow' => true,
//                        'roles' => ['@'],
//                    ],
//                ],
//            ],
//            // 'verbs' => [
//            //     'class' => VerbFilter::className(),
//            //     'actions' => [
//            //         'logout' => ['post'],
//            //     ],
//            // ],
//        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        // $this->layout = "@app/views/layouts/main-adm";
        // return $this->render('index');
//        if (Yii::$app->user->isGuest)
//            return $this->redirect(['adm/login']);

        return $this->redirect(['adm/home']);
    }

    public function actionHome()
    {
        // $role = Yii::$app->user->identity->role;
        // $type = Yii::$app->user->identity->type;
        // if($type == "User Eksekutif")
        // {
        //     return $this->redirect('../dashboard/cockpit');
        // }
        // else
        // {
        //     if($role == "UnitKerja" || $role == "UnitBisnis" || $role == "Direktorat") {
        //         return $this->redirect('../dashboard/landingpage');
        //     } elseif($role == "UnitBa") {
        //         return $this->redirect('../monitoring/default/juskeb');
        //     } else {
        //         return $this->redirect('../dashboard');
        //     }
        // }
        // $this->layout = true;
        return $this->render('home');
    }

    public function actionCreate()
    {
        $model = new Artikel();
        // $file = isset($_FILES['file_items']) ? $_FILES['file_items'] : null;
        if ($model->load(Yii::$app->request->post())) {
            // if(!is_null($file) || $file['error'] == 0 )
            // {
                // $RootTmp = \Yii::getAlias('@app') . '/web/uploads/img_artikel/';
                // if (!is_dir($RootTmp)) { mkdir($RootTmp);}
                // chmod($RootTmp, 0777);
                //
                // $path     = $file['name'];
                // $dateRand = date('YmdHis',time())."-".mt_rand();
                // $file_name= $dateRand."_".$path;
                // $newpath  = \Yii::getAlias('@app') . '/web/uploads/img_artikel/'.$path;
                // move_uploaded_file($file['tmp_name'], $newpath);

                $model->judul = $_POST['Artikel']['judul'];
                $model->desc = $_POST['Artikel']['desc'];
                $model->gambar = $_POST['Artikel']['gambar'];
                $model->mini_desc = $_POST['Artikel']['mini_desc'];
                $model->tgl_event = $_POST['Artikel']['tgl_event'];
                $model->valid_until = $_POST['Artikel']['valid_until'];
                $model->created_by = Yii::$app->user->identity->username;
                $model->created_at = date('Y-m-d H:i:s');
                if ($model->save()) {
                    $hasil = array(
                        'status' => "success",
                        'header' => "Berhasil",
                        'message' => "Artikel Berhasil Di Tambahkan !",
                    );
                    echo json_encode($hasil);
                    die();
                }
            // }
        }

        return $this->renderPartial('create', [
            'model' => $model,
        ]);
    }

    public function actionCreatedet($id)
    {
        $model = new ArtikelDetail();
        $model2 = Artikel::find()->where(['id' => $id])->asArray()->one();
        // $file = isset($_FILES['file_items']) ? $_FILES['file_items'] : null;
        if ($model->load(Yii::$app->request->post())) {
                $harga = $_POST['ArtikelDetail']['harga'];
                $r_harga = str_replace(',','',$harga);
                // var_dump($r_harga);exit();
            // if(!is_null($file) || $file['error'] == 0 )
            // {
                // $RootTmp = \Yii::getAlias('@app') . '/web/uploads/img_artikel/';
                // if (!is_dir($RootTmp)) { mkdir($RootTmp);}
                // chmod($RootTmp, 0777);
                //
                // $path     = $file['name'];
                // $dateRand = date('YmdHis',time())."-".mt_rand();
                // $file_name= $dateRand."_".$path;
                // $newpath  = \Yii::getAlias('@app') . '/web/uploads/img_artikel/'.$path;
                // move_uploaded_file($file['tmp_name'], $newpath);

                $model->id_artikel = $id;
                $model->ket = $_POST['ArtikelDetail']['ket'];
                $model->jml_tiket = $_POST['ArtikelDetail']['jml_tiket'];
                $model->jml_terjual = $_POST['ArtikelDetail']['jml_terjual'];
                $model->harga = (string) $r_harga;
                $model->sesi = $_POST['ArtikelDetail']['sesi'];
                $model->jam_tayang = $_POST['ArtikelDetail']['jam_tayang'];
                $model->created_by = Yii::$app->user->identity->username;
                $model->created_at = date('Y-m-d H:i:s');
                if ($model->save()) {
                    $hasil = array(
                        'status' => "success",
                        'header' => "Berhasil",
                        'message' => "Detail Artikel Berhasil Di Tambahkan !",
                    );
                    echo json_encode($hasil);
                    die();
                }
            // }
        }

        return $this->renderPartial('create_det', [
            'model' => $model,
            'model2' => $model2,
            'id' => $id
        ]);
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post())) {
            $model->judul = $_POST['Artikel']['judul'];
            $model->desc = $_POST['Artikel']['desc'];
            $model->gambar = $_POST['Artikel']['gambar'];
            $model->mini_desc = $_POST['Artikel']['mini_desc'];
            $model->tgl_event = $_POST['Artikel']['tgl_event'];
            $model->valid_until = $_POST['Artikel']['valid_until'];
            $model->created_by = Yii::$app->user->identity->username;
            $model->updated_at = date('Y-m-d H:i:s');
            if ($model->save()) {
                $hasil = array(
                    'status' => "success",
                    'header' => "Berhasil",
                    'message' => "Artikel Berhasil Di Update !",
                );
                echo json_encode($hasil);
                die();
            }
        }

        return $this->renderPartial('update', [
            'model' => $model,
            'id' => $id,
        ]);
    }

    public function actionUpdatedet($id)
    {
        $model = $this->findModel2($id);
        $model2 = Artikel::find()->where(['id' => $model->id_artikel])->asArray()->one();
        // var_dump($model2);exit();
        if ($model->load(Yii::$app->request->post())) {
            $harga = $_POST['ArtikelDetail']['harga'];
            $r_harga = str_replace(',','',$harga);

            $model->ket = $_POST['ArtikelDetail']['ket'];
            $model->jml_tiket = $_POST['ArtikelDetail']['jml_tiket'];
            $model->jml_terjual = $_POST['ArtikelDetail']['jml_terjual'];
            $model->harga = (string) $r_harga;
            $model->sesi = $_POST['ArtikelDetail']['sesi'];
            $model->jam_tayang = $_POST['ArtikelDetail']['jam_tayang'];
            $model->updated_by = Yii::$app->user->identity->username;
            $model->updated_at = date('Y-m-d H:i:s');
            if ($model->save()) {
                $hasil = array(
                    'status' => "success",
                    'header' => "Berhasil",
                    'message' => "Detail Artikel Berhasil Di Update !",
                );
                echo json_encode($hasil);
                die();
            }
        }

        return $this->renderPartial('update_det', [
            'model' => $model,
            'model2' => $model2,
            'id' => $id
        ]);
    }

    public function actionDetartikel($id)
    {
        // $model = $this->findModel($id);
        $modelArtikel = Artikel::find()->where(['id' => $id])->asArray()->one();

controllers/UsersController.php
<?php

namespace app\controllers;

use Yii;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Users;

class UsersController extends \yii\web\Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
//        print_r(Yii::$app->user->identity->username);exit;
        $this->layout = "@app/views/layouts/main-adm";
        return $this->render('index');
    }

    public function actionCreate()
    {
        // var_dump($_POST);exit();
        $model = new Users();
        if ($model->load(Yii::$app->request->post())) {
                $model->username = $_POST['Users']['username'];
                $model->password = sha1($_POST['Users']['password']);
                $model->email = $_POST['Users']['email'];
                $model->role = $_POST['Users']['role'];
                $model->created_at = date('Y-m-d H:i:s');
                if ($model->save()) {
                    $hasil = array(
                        'status' => "success",
                        'header' => "Berhasil",
                        'message' => "Users Berhasil Di Tambahkan !",
                    );
                    echo json_encode($hasil);
                    die();
                }
        }

        return $this->renderPartial('create', [
            'model' => $model,
        ]);
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post())) {
            $model->username = $_POST['Users']['username'];
            $model->password = sha1($_POST['Users']['password']);
            $model->email = $_POST['Users']['email'];
            $model->role = $_POST['Users']['role'];
            $model->updated_at = date('Y-m-d H:i:s');
            if ($model->save()) {
                $hasil = array(
                    'status' => "success",
                    'header' => "Berhasil",
                    'message' => "Users Berhasil Di Update !",
                );
                echo json_encode($hasil);
                die();
            }
        }

        return $this->renderPartial('update', [
            'model' => $model,
            'id' => $id,
        ]);
    }

    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        $hasil = array(
            'status' => "success",
            'header' => "Berhasil",
            'message' => "Users Berhasil Di Hapus !",
        );
        echo json_encode($hasil);
        die();
        // return $this->redirect(['adm/artikel']);
    }

    public function actionGetdatausers()
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;

        $data = Users::find()->asArray()->all();

        $row = array();
        $i = 0;
        foreach ($data as $idx => $value) {
            //Asiign All Value To Row
            foreach ($value as $key => $val) {
                $row[$i][$key] = $val;
            }
            $row[$i]['username'] = $value['username'];
            $row[$i]['email'] = $value['email'];
            $row[$i]['role'] = $value['role'];
            $row[$i]['fungsi'] = "
                <button onclick='updateusers(\"" . $value['id'] . "\")' type='button' rel='tooltip' data-toggle='tooltip' title='Edit Users' class='btn btn-sm btn-warning'><i class='fa fa-edit'></i></button>
                <button onclick='deleteusers(\"" . $value['id'] . "\")' type='button' rel='tooltip' data-toggle='tooltip' title='Hapus Users' class='btn btn-sm btn-danger'><i class='fa fa-trash'></i></button>
            ";
            $i++;
        }
        $hasil['data'] = $row;
            // var_dump($hasil);exit();
        return $hasil;
    }

    protected function findModel($id)
    {
        if (($model = Users::findOne($id)) !== null) {
            return $model;
        }
        throw new NotFoundHttpException('The requested page does not exist.');
    }


}

views/adm/_viewtbl.php
<table id="tbl_detartikel" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th style="width:5px;">ID.</th>
            <th>Deskripsi</th>
            <th>Jumlah Tiket</th>
            <th>Jumlah Terjual</th>
            <th>Harga</th>
            <th>Sesi</th>
            <th>Jam Tayang</th>
            <th>Action</th>
        </tr>
    </thead>
</table>

<script>
// var t = null;
$(document).ready(function () {
    var idartikel = <?=$_GET['idartikel']?>;
    // alert(idartikel);
    // t.destroy();

   $('#tbl_detartikel').DataTable({
       scrollY:        "170px",
       scrollX:        true,
       scrollCollapse: true,
       columnDefs: [
           {
               // width: '35%', targets: 0,
               "targets": [ 0 ],
               "visible": false,
           },
           // { width: '15%', targets: 1 },
           // { width: '15%', targets: 2 },
           // { width: '15%', targets: 3 },
           // { width: '20%', targets: 4 }
       ],
       fixedColumns: true,
        "ajax": '<?php echo \Yii::$app->getUrlManager()->createUrl("adm/getdatadetartikel");?>?idartikel='+idartikel,
        "columns": [
            {"data": "id"},
            {"data": "ket"},
            {"data": "jml_tiket"},
            {"data": "jml_terjual"},
            {"data": "harga"},
            {"data": "sesi"},
            {"data": "jam_tayang"},
            {
                "orderable": false,
                "data": 'fungsi',
                "defaultContent": ''
            },

        ],
        "order": [[0, 'desc']]
    });
});
</script>

views/adm/artikel.php
<?php
/**
 * Created by PhpStorm.
 * Project : tiketing
 * User: fahmihilmansyah
 * Date: 2018-12-18
 * Email : fahmi.hilmansyah@gmail.com
 * Telp : 0817170820
 * Time: 00:09
 * Dilarang Keras Mengubah atau Mendistribusikan ulang code ini tanpa sepengetahuan.
 */
 ?>
 <?php

 use yii\bootstrap\ActiveForm;
 use yii\helpers\Html;

 // use fedemotta\datatables\DataTables;

 /* @var $this yii\web\View */
 /* @var $searchModel app\models\PAsetKategoriSearch */
 /* @var $dataProvider yii\data\ActiveDataProvider */

 $this->title = 'Artikel';
 $this->params['breadcrumbs'][] = $this->title;
 ?>
 <style type="text/css">
     .mright {
         margin-right: 5px;
     }

    .modal-lg {
        max-width: 90%;
    }
    /* .swal-modal {
        z-index: 99999999 !important;
    } */
    #modalDetArtikel {
        z-index: 20000000 !important;
        /* overflow-y: hidden; */
    }
    #modalArtikel {
        z-index: 10000000 !important;
        /* overflow-y: hidden; */
    }

    .modal-body {
        overflow-y: hidden !important;
    }

    /* Ensure that the demo table scrolls */
    th, td { white-space: nowrap; }
    div.dataTables_wrapper {
        margin: 0 auto;
    }

    div.container {
        width: 80%;
    }
 </style>
 <div class="menuartikel-index">

     <h1 class="title"><?= Html::encode($this->title) ?></h1>

     <!-- <p class="pull-right"> -->
     <div class="row">
         <div class="col-md-12" align="right" style="margin-bottom:5px;">
             <?= Html::a('<i class="fa fa-plus"></i> Buat Artikel', 'javascript:addartikel()', ['class' => 'btn btn-sm btn-success']) ?>
         </div>
     </div>

     <?php
     $form = ActiveForm::begin([
         "options" => [
             "class" => "",
             // "id"    => "form-filter-juskeb",
             // 'onsubmit'=>'return true;',
         ]
     ]);
     ?>
    <div class="card">
       <!-- /.card-header -->
       <div class="card-body">
         <table id="tbl_artikel" class="table table-bordered table-striped">
                 <thead>
                 <tr>
                     <th style="width:5px;">ID.</th>
                     <th>Judul</th>
                     <th>Mini Deskripsi</th>
                     <!-- <th>Deskripsi</th> -->
                     <th>Tgl.Event</th>
                     <th>Valid Until</th>
                     <th>Action</th>
                 </tr>
                 </thead>
             </table>

         </div>
    </div>
     <?php ActiveForm::end(); ?>
 </div>

 <div id="modalArtikel" class="modal fade bs-example-modal" role="dialog" aria-hidden="true">
     <div class="modal-dialog modal-lg">
         <div class="modal-content">
             <div class="modal-header">
                 <h4 class="modal-title" id="modalTitleArtikel"></h4>
                 <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span></button>
             </div>
             <div class="modal-body table-responsive" id="modalBodyArtikel">
                 Loading ...
             </div>
             <!-- <div class="modal-footer">
               <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
               <button type="button" class="btn btn-primary" id="modalBtnSave">Save changes</button>
             </div> -->
         </div>
     </div>
 </div>

 <div id="modalDetArtikel" class="modal fade bs-example-modal" role="dialog" aria-hidden="true">
     <div class="modal-dialog modal-lg">
         <div class="modal-content">
             <div class="modal-header">
                 <h4 class="modal-title" id="modalTitleDetArtikel"></h4>
                 <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span></button>
             </div>
             <div class="modal-body table-responsive" id="modalBodyDetArtikel">
                 Loading ...
             </div>
             <!-- <div class="modal-footer">
               <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
               <button type="button" class="btn btn-primary" id="modalBtnSave">Save changes</button>
             </div> -->
         </div>
     </div>
 </div>


 <script type="text/javascript">
     // var t = null;
     $(document).ready(function () {
         // t.destroy();

        $('#tbl_artikel').DataTable({
        //      "processing": true,
        // "serverSide": true,
        scrollY:        "300px",
        scrollX:        true,
        scrollCollapse: true,
        columnDefs: [
            {
                // width: '20%', targets: 0,
                "targets": [ 0 ],
                "visible": false,
            },
            // { width: '35%', targets: 1 },
            // { width: '15%', targets: 2 },
            // { width: '15%', targets: 3 },
            // { width: '15%', targets: 4 }
        ],
        fixedColumns: true,
             "ajax": '<?php echo \Yii::$app->getUrlManager()->createUrl("adm/getdataartikel");?>',
             "columns": [
                 {"data": "id"},
                 {"data": "judul"},
                 {"data": "mini_desc"},
                 // {"data": "desc"},
                 {"data": "tgl_event"},
                 {"data": "valid_until"},
                 {
                     "orderable": false,
                     "data": 'fungsi',
                     "defaultContent": ''
                 },

             ],
             "order": [[0, 'desc']]
         });
     });

     function addartikel() {
         var url = "<?php echo \Yii::$app->getUrlManager()->createUrl(['adm/create']);?>";
         var title = "Buat Artikel";
         showModal(url, title);
     }

     function adddetartikel(id) {
         var url = "<?php echo \Yii::$app->getUrlManager()->createUrl(['adm/createdet']);?>?id=" + id;
         var title = "Buat Detail Artikel";
         showModalDetArtikel(url, title);
     }

     function updateartikel(id) {
         var url = "<?php echo \Yii::$app->getUrlManager()->createUrl(['adm/update']);?>?id=" + id;
         var title = "Update Artikel";
         showModal(url, title);
     }

     function updatedetartikel(id) {
         var url = "<?php echo \Yii::$app->getUrlManager()->createUrl(['adm/updatedet']);?>?id=" + id;
         var title = "Update Detail Artikel";
         showModalDetArtikel(url, title);
     }

     function detailartikel(id) {
         var url = "<?php echo \Yii::$app->getUrlManager()->createUrl(['adm/detartikel']);?>?id=" + id;
         var title = "Detail Artikel";
         showModal(url, title);
     }

     function showModal(url, title) {
         $("#modalTitleArtikel").empty();
         $("#modalTitleArtikel").html(title);

         $("#modalBodyArtikel").empty();
         $("#modalBodyArtikel").html("Loading ...");
         $("#modalBodyArtikel").load(url);

         $('#modalArtikel').modal({backdrop: 'static', keyboard: false});
         $("#modalArtikel").modal("show");
         return false;
     }

     function showModalDetArtikel(url, title) {
         $("#modalTitleDetArtikel").empty();
         $("#modalTitleDetArtikel").html(title);

         $("#modalBodyDetArtikel").empty();
         $("#modalBodyDetArtikel").html("Loading ...");
         $("#modalBodyDetArtikel").load(url);

         $('#modalDetArtikel').modal({backdrop: 'static', keyboard: false});
         $("#modalDetArtikel").modal("show");
         return false;
     }

     function deleteartikel(id) {
         {
             swal({
                 title: "Konfirmasi",
                 text: "Hapus Artikel ini?",
                 icon: "warning",
                 buttons: true,
                 dangerMode: true,
             }).then((ya) => {
                 if (ya) {
                     $.ajax({
                         type: "GET",
                         // data: {id:id},
                         dataType: "json",
                         contentType: false,
                         processData: false,
                         url: "<?=\Yii::$app->getUrlManager()->createUrl(['adm/delete'])?>?id=" + id,
                         beforeSend: function () {
                             swal({
                                 title: 'Harap Tunggu',
                                 text: "Sedang Menghapus Menu",
                                 icon: 'info',
                                 buttons: {
                                     cancel: false,
                                     confirm: false,
                                 },
                                 closeOnClickOutside: false,
                                 onOpen: function () {
                                     swal.showLoading()
                                 },
                                 closeOnEsc: false,
                             });
                         },
                         complete: function () {
                             swal.close()
                         },
                         success: function (result) {

                             swal(result.header, result.message, result.status);

                             if (result.status == "success") {
                                 window.location = "<?=\Yii::$app->getUrlManager()->createUrl(['adm/artikel'])?>";
                             }
                         },
                         error: function (xhr, ajaxOptions, thrownError) {
                             swal("Error!", "Terdapat Kesalahan saat menghapus Menu!", "error");
                         }
                     });
                 } else {

                 }
             });
         }

     }
 </script>

views/adm/create.php
<?php


/* @var $this yii\web\View */
/* @var $model app\models\Artikel */

?>
<div class="artikel-create">

    <?= $this->render('_form', [
        'model' => $model
    ]) ?>

</div>

views/adm/create_det.php
<?php


/* @var $this yii\web\View */
/* @var $model app\models\Artikel */

?>
<div class="detartikel-create">

    <?= $this->render('_formdet', [
        'model' => $model,
        'model2' => $model2,
        'id' => $id
    ]) ?>

</div>

views/adm/home.php
<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

// use fedemotta\datatables\DataTables;

/* @var $this yii\web\View */
/* @var $searchModel app\models\PAsetKategoriSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Home';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="menuartikel-index">

    <h1 class="title"><?= Html::encode($this->title) ?></h1>
</div>

views/adm/index.php
 <?php

 use yii\bootstrap\ActiveForm;
 use yii\helpers\Html;

 // use fedemotta\datatables\DataTables;

 /* @var $this yii\web\View */
 /* @var $searchModel app\models\PAsetKategoriSearch */
 /* @var $dataProvider yii\data\ActiveDataProvider */

 $this->title = 'Home';
 $this->params['breadcrumbs'][] = $this->title;
 ?>
 <div class="menuartikel-index">

     <h1 class="title"><?= Html::encode($this->title) ?></h1>
</div>

views/adm/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Tiketing';
// $this->params['breadcrumbs'][] = $this->title;
?>

<div class="login-box">
    <div class="login-logo">
        <h1><?= Html::encode($this->title) ?></h1>
    </div>
  <!-- /.login-logo -->
    <div class="card">
        <div class="card-body login-card-body">
          <p class="login-box-msg">Control Management System</p>

            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
            <div class="form-group has-feedback">
                <input type="text" name="LoginForm[username]" class="form-control" placeholder="Username">
                <!-- <span class="fa fa-envelope form-control-feedback"></span> -->
                <p class="help-block help-block-error" style="color:#fff!important">
                    <?php
                    if (!empty($model->errors)) {
                      if (isset($model->errors['username'][0]))
                          echo $model->errors['username'][0];
                    }
                    ?>
                </p>
            </div>
            <div class="form-group has-feedback">
                <input type="password" name="LoginForm[password]" class="form-control" placeholder="Password">
                <!-- <span class="fa fa-lock form-control-feedback"></span> -->
                <p class="help-block help-block-error" style="color:#fff!important">
                    <?php
                    if (!empty($model->errors)) {
                      if (isset($model->errors['password'][0]))
                          echo $model->errors['password'][0];
                    }
                    ?>
                </p>
            </div>
            <div class="row">
                <!-- /.col -->
                <!-- <div class="col-4"> -->
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary btn-block', 'name' => 'login-button']) ?>
                <!-- </div> -->
                <!-- /.col -->
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/adm/update.php
<?php


/* @var $this yii\web\View */
/* @var $model app\models\Artikel */

?>
<div class="artikel-update">

    <?= $this->render('_form', [
        'model' => $model,
        'id' => $id
    ]) ?>

</div>

views/adm/update_det.php
<?php


/* @var $this yii\web\View */
/* @var $model app\models\Artikel */

?>
<div class="detartikel-update">

    <?= $this->render('_formdet', [
        'model' => $model,
        'model2' => $model2,
        'id' => $id
    ]) ?>

</div>