controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Artikel;
use app\models\ArtikelDetail;
use app\models\Member;
use app\models\TiketBooking;
use Yii;
use yii\db\Expression;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    function actionFronts()
    {
        $this->layout = "@app/views/layouts/main-front";
        $getarticle = (new Query())->from('artikel')->all();
        $data['artikel'] = $getarticle;
        return $this->render('front', $data);
    }

    function actionGetlisttiket()
    {

    }

    function actionArtikelbyr($id = null)
    {

        $getdetail = ArtikelDetail::find()->where(['id_artikel' => $id])->andWhere(['>', 'jml_tiket', 'jml_terjual'])->all();
        if (!empty($getdetail)):
            $getartikel = Artikel::find()->where(['id' => $id])->andWhere(['>=', 'valid_until', date('Y-m-d')])->one();
            if(!empty($getartikel)){
                $parsing=array();
                foreach($getdetail as $r){
                    $sesi = strtolower(str_replace(' ','',$r['sesi']));
                    $jam_tayang = str_replace(':','',$r['jam_tayang']);

                    if(!isset($parsing[$sesi.$jam_tayang])){
                        $parsing[$sesi.$jam_tayang]['sesi']=$r['sesi'];
                        $parsing[$sesi.$jam_tayang]['jam_tayang']=date("H:i",strtotime($r['jam_tayang']));
                        $parsing[$sesi.$jam_tayang][]=array(
                            'id'=>$r['id'],
                            'id_artikel'=>$r['id_artikel'],
                            'jml_tiket'=>$r['jml_tiket'],
                            'ket'=>$r['ket'],
                            'jml_terjual'=>$r['jml_terjual'],
                            'harga'=>$r['harga'],
                        );
                    }else{
                        $parsing[$sesi.$jam_tayang]['sesi']=$r['sesi'];
                        $parsing[$sesi.$jam_tayang]['jam_tayang']=date("H:i",strtotime($r['jam_tayang']));
                        $parsing[$sesi.$jam_tayang][]=array(
                            'id'=>$r['id'],
                            'id_artikel'=>$r['id_artikel'],
                            'jml_tiket'=>$r['jml_tiket'],
                            'ket'=>$r['ket'],
                            'jml_terjual'=>$r['jml_terjual'],
                            'harga'=>$r['harga'],
                            'sesi'=>$r['sesi'],
                            'jam_tayang'=>$r['jam_tayang'],
                        );
                    }
                }
                $data['artikel'] = $getartikel;
                $data['artikel_detail'] = $parsing;
                return $this->renderPartial('modalbuy', $data);
            }else{
                echo " Data Tiket Habis / Tidak Tersedia.";
                exit;
            }
        else:
            echo " Data Tiket Habis / Tidak Tersedia.";
            exit;
        endif;
    }

    function actionBuytiket()
    {
        if ($_POST) {
            $req = Yii::$app->request->post();
            if(!isset($req['detailprod'])){
                echo "ada kesalahan sistem";exit;
            }
            $iddetail = $req['detailprod'];
            $idproduk = $req['idproduk'];
            $jmlbook = $req['jmlbook'];
            $namapesan = $req['namapesan'];
            $tempatlahir = $req['tempatlahir'];
            $tgl_lahir = $req['tgl_lahir'];
            $domisili = $req['domisili'];
            $no_telp = $req['no_telp'];
            $email = $req['email'];
            if (!$this->validateEmail($email)) {
                echo "email not valid";
                exit;
            } else {
                $transaction = Yii::$app->db->beginTransaction();
                try {
                    $harga = ArtikelDetail::find()
                        ->where(['id' => $iddetail])
                        ->andWhere(['>', 'jml_tiket', 'jml_terjual'])
                        ->one();
                    $findmember = Member::find()->where(['email' => $email])->orWhere(['phone' => $no_telp])->one();
                    if (!empty($harga)):
                        $idmember = uniqid();
                        if (!empty($findmember)) {
                            $idmember = $findmember->id;
                        } else {
                            $member = new Member();
                            $member->id = $idmember;
                            $member->fullname = $namapesan;
                            $member->email = $email;
                            $member->phone = $no_telp;
                            $member->tgl_lahir = $tgl_lahir;
                            $member->tempat_lahir = $tempatlahir;
                            $member->domisili = $domisili;
                            $member->created_by = 'GUEST';
                            $member->created_at = date("Y-m-d H:i:s");
                            $member->updated_at = date("Y-m-d H:i:s");
                            if (!$member->save()) {
                                echo "Error Member";
                                print_r($member->errors);
                            }
                        }
                        $tiketbook = new TiketBooking();
                        $orderno = rand(0,999999999);
                        $getdisokon = 0;//$this->hitungDiskon($jmlbook);
                        $total = ($getdisokon > 0)?($jmlbook * $harga['harga']) - (($jmlbook * $harga['harga'])*($getdisokon/100)):($jmlbook * $harga['harga']);

//                        echo $total." ".$getdisokon;exit;
                        $tiketbook->id_artikel_detail = $iddetail;
                        $tiketbook->id_member = $idmember;
                        $tiketbook->jml_tiket = $jmlbook;
                        $tiketbook->harga = $harga['harga'];
                        $tiketbook->jenis = 'ONLINE';
                        $tiketbook->diskon = (string)$getdisokon;
                        $tiketbook->total_harga = (string)$total ;
                        $tiketbook->status = $total == 0 ?"konfirmasi":'waiting';
                        $tiketbook->no_order = (string)$orderno;
                        $tiketbook->created_by = date("Y-m-d H:i:s");
                        $tiketbook->updated_by = date("Y-m-d H:i:s");
                        if (!$tiketbook->save()) {
                            echo "Error Tiket Book";
                            print_r($tiketbook->errors);
                        }
                        $harga->jml_terjual = $harga->jml_terjual + $jmlbook;
                        $harga->updated_at = date("Y-m-d H:i:s");
                        if (!$harga->save()) {
                            echo "Error Harga";
                            print_r($harga->errors);
                        }

                        $total = $harga->harga * $jmlbook;
                        $this->kirimEmail($email, $namapesan, number_format($total, 0, '', '.'),$orderno);
                    endif;
                    $transaction->commit();
                } catch (Exception $e) {
                    $transaction->rollback();
                }
            }

            return $this->redirect(Url::to(['/info/index','order'=>$orderno]));
        }
        return $this->redirect(Url::to(['/']));
    }
    function hitungDiskon($jml){
        $diskon = 0;

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/front.php
<!-- =============== START OF HOW IT WORKS SECTION =============== -->
<section class="how-it-works3 ptb100" id="belitiketnya">
    <div class="container">

        <!-- Start of row -->
        <div class="row justify-content-center">
            <div class="col-md-7 text-center">
                <h2 class="title" style="padding-bottom: 0px;">Beli tiketnya </h2>
                <hr>
            </div>
        </div>
        <!-- End of row -->

        <!-- Start of row -->

        <div id="daftarmain">
            <div class="row justify-content-center">
                <?php foreach ($artikel as $r): ?>
                    <div class="col-md-3">
                        <div class="card hoverable" testmasuk="masuk">
                            <div class="img-card" style="background-image:url(<?php echo $r['gambar'] ?>)"></div>
                            <div class="card-body small-pad card-artikel">
                                <h6 class="card-title mt-0 mb-5"><?php echo $r['judul'] ?></h6>
                                <p class="text-small text-muted lh-n"><?php echo $r['mini_desc'] ?></p>
                                <div class="text-center">
                                    <span data-url="<?php  echo  str_replace('http://','https://',\yii\helpers\Url::to(['/site/artikelbyr','id'=>$r['id']],true))?>" href="#" class="btn btn-primary buytiketing"><?php echo $r['is_tiket'] == '1'? '<span class="fa fa-shopping-cart"></span> &nbsp; Beli Tiket':'<span class="fa fa-user"></span> &nbsp; Registrasi'?></span>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>

    </div>
</section>

<!-- Modal -->
<div class="modal fade" id="beli" tabindex="-1" role="dialog" aria-labelledby="beliLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="beliLabel">Order</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modaldata">

            </div>
        </div>
    </div>
</div>

<!-- =============== END OF HOW IT WORKS SECTION =============== -->

<!-- =============== START OF LATEST RELEASES SECTION =============== -->
<script>
    $(".buytiketing").on('click',function () {
        let attrurl = $(this).attr('data-url');
        // $("#beli").modal().load()
        $("#modaldata").empty();
        $('#beli').modal('show').find('.modal-body').load(attrurl);
    })

</script>

views/site/index.php
<?php

/* @var $this yii\web\View */
$this->title = 'My Yii Application';
?>
<div class="site-index">

<!--    <div class="jumbotron">-->
<!--        <h1>Congratulations!</h1>-->
<!---->
<!--        <p class="lead">You have successfully created your Yii-powered application.</p>-->
<!---->
<!--        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>-->
<!--    </div>-->
    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleCaptions" data-slide-to="0" class=""></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="1" class=""></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="2" class="active"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item">
                <img class="d-block w-100" data-src="holder.js/800x400?auto=yes&amp;bg=777&amp;fg=555&amp;text=First slide" alt="First slide [800x400]" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22800%22%20height%3D%22400%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20800%20400%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_16795e5b62e%20text%20%7B%20fill%3A%23555%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A40pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_16795e5b62e%22%3E%3Crect%20width%3D%22800%22%20height%3D%22400%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22285.921875%22%20y%3D%22218.45%22%3EFirst%20slide%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true">
                <div class="carousel-caption d-none d-md-block">
                    <h5>First slide label</h5>
                    <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" data-src="holder.js/800x400?auto=yes&amp;bg=666&amp;fg=444&amp;text=Second slide" alt="Second slide [800x400]" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22800%22%20height%3D%22400%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20800%20400%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_16795e5b62f%20text%20%7B%20fill%3A%23444%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A40pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_16795e5b62f%22%3E%3Crect%20width%3D%22800%22%20height%3D%22400%22%20fill%3D%22%23666%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22247.3203125%22%20y%3D%22218.45%22%3ESecond%20slide%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Second slide label</h5>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                </div>
            </div>
            <div class="carousel-item active">
                <img class="d-block w-100" data-src="holder.js/800x400?auto=yes&amp;bg=555&amp;fg=333&amp;text=Third slide" alt="Third slide [800x400]" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22800%22%20height%3D%22400%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20800%20400%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_16795e5b630%20text%20%7B%20fill%3A%23333%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A40pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_16795e5b630%22%3E%3Crect%20width%3D%22800%22%20height%3D%22400%22%20fill%3D%22%23555%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22277%22%20y%3D%22218.45%22%3EThird%20slide%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Third slide label</h5>
                    <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

</div>

views/site/modalbuy.php
<?php
/**
 * Created by PhpStorm.
 * Project : tiketing
 * User: fahmihilmansyah
 * Date: 2018-12-20
 * Email : fahmi.hilmansyah@gmail.com
 * Telp : 0817170820
 * Time: 11:12
 * Dilarang Keras Mengubah atau Mendistribusikan ulang code ini tanpa sepengetahuan.
 */
?>
<div class="row mb-15">
    <div class="col-md-5">
        <img src="<?php echo $artikel['gambar'] ?>" class="img-content"/>
    </div>
    <div class="col-md-7">
        <div class="desc-content">
            <h6 class="card-title mt-0 mb-5"><?php echo $artikel['judul'] ?></h6>
            <p class="lh-n">
                <?php echo $artikel['mini_desc'] ?>
            </p>
        </div>
    </div>
</div>
<hr>
<?php echo \yii\helpers\Html::beginForm(\yii\helpers\Url::to(['/site/buytiket'], true), 'POST'); ?>

<ul class="nav nav-pills oneline" id="myTab" role="tablist">
    <?php foreach ($artikel_detail as $k => $v): ?>
        <li class="nav-item">
            <a class="nav-link" id="<?php echo $k ?>-tab" data-toggle="tab" href="#<?php echo $k ?>" role="tab"
               aria-controls="<?php echo $k ?> aria-selected="
               true"><?php echo $v['sesi'] . " " . $v['jam_tayang'] ?></a>
        </li>
    <?php endforeach; ?>
</ul>
<div class="tab-content" id="myTabContent">
    <?php foreach ($artikel_detail as $k => $v): ?>
        <div class="tab-pane fade" id="<?php echo $k ?>" role="tabpanel" aria-labelledby="profile-tab">
            <div class="form-group">
                <?php
                foreach ($v as $kr => $vr):
                    if (is_array($vr)):
                        $i = 1;
                        ?>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input required type="radio" id="customRadioInline<?php echo $vr['id'] ?>" name="detailprod"
                                   value="<?php echo $vr['id'] ?>" class="custom-control-input">
                            <label class="custom-control-label"
                                   for="customRadioInline<?php echo $vr['id'] ?>"><?php echo $vr['ket'] . " (" . number_format($vr['harga'], 0, '', '.') . ")" ?></label>
                        </div>
                        <?php $i++;
                    endif;
                endforeach; ?>
            </div>
        </div>
    <?php endforeach; ?>
</div>
<input type="hidden" name="idproduk" value="<?php echo $_GET['id'] ?>">
<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            <label>Jumlah Booking</label>
            <input type="number" name="jmlbook" required class="form-control" value="1"
                   placeholder="Tulis Jumlah Booking Anda">
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label>Nama</label>
            <input type="text" name="namapesan" required class="form-control" placeholder="Tulis Nama Anda">
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label>Tempat Lahir</label>
            <input type="text" name="tempatlahir" required class="form-control" placeholder="Tulis Tempat Lahir Anda">
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label>Tanggal Lahir</label>
            <input type="date" name="tgl_lahir" required class="form-control" placeholder="">
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label>Tlp / HP</label>
            <input type="text" name="no_telp" required class="form-control" placeholder="Tulis Nomor Tlp / HP Anda">
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label>Email</label>
            <input type="email" name="email" required class="form-control" placeholder="Tulis Email Anda">
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label>Domisili</label>
            <input type="text" name="domisili" required class="form-control" placeholder="Tulis Domisili Anda">
        </div>
    </div>
</div>
<button class="btn btn-primary"><?php echo $artikel['is_tiket'] == '1' ?'<i class="fa fa-check"></i> Beli Sekarang':'<i class="fa fa-check"></i> Registrasi Sekarang' ?></button>
<?php \yii\helpers\Html::endForm(); ?>