models/User.php
<?php

namespace app\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;


class User extends ActiveRecord implements \yii\web\IdentityInterface
{
    public $id;
    public $username;
    public $password;
    public $role;
    public $email;
    /*
    public $id;
    public $username;
    public $password;
    public $authKey;
    public $accessToken;

    private static $users = [
        '100' => [
            'id' => '100',
            'username' => 'admin',
            'password' => 'admin',
            'authKey' => 'test100key',
            'accessToken' => '100-token',
        ],
        '101' => [
            'id' => '101',
            'username' => 'demo',
            'password' => 'demo',
            'authKey' => 'test101key',
            'accessToken' => '101-token',
        ],
    ];
    */

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'users';
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        // return isset(self::$users[$id]) ? new static(self::$users[$id]) : null;
        $user = Users::find()->where(['username' => $id])->asArray()->one();
        $identity = new User();
        $identity->id           = $id;
        $identity->username     = $id;
        $identity->email        = $user['email'];
        $identity->role         = $user['role'];

        return $identity;
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        /*foreach (self::$users as $user) {
            if ($user['accessToken'] === $token) {
                return new static($user);
            }
        }

        return null;
        */

        return static::findOne(['access_token' => $token]);
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        /*foreach (self::$users as $user) {
            if (strcasecmp($user['username'], $username) === 0) {
                return new static($user);
            }
        }

        return null;
        */

        return static::findOne(['username' => $username]);
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        // return $this->password === $password;
        return  $this->password === sha1($password);
    }


    public function setPassword($password)
    {
        $this->password = sha1($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->authKey = Yii::$app->security->generateRandomString();
    }

}

models/Users.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;

/**
 * This is the model class for table "users".
 *
 * @property integer $id
 * @property string $username
 * @property string $authKey
 * @property string $password
 * @property string $email
 * @property string $accessToken
 * @property string $created_at
 * @property string $updated_at
 * @property integer $role
 */
class Users extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'users';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username','password','email'],'required','on'=>'create'],
            [['role'], 'integer'],
            [['username', 'password', 'email','updated_at','created_at'], 'string', 'max' => 255],
            [['authKey', 'accessToken'], 'string', 'max' => 32],
            [['username'], 'unique'],
            [['email'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Username',
            'authKey' => 'Auth Key',
            'password' => 'Password',
            'email' => 'Email',
            'accessToken' => 'Access Token',
            'role' => 'Role',
            'buscd' => 'Perusahaan',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

     public function search($params)
    {
        $query = users::find();

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $this->load($params);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }

        $query->andFilterWhere([
            'id' => $this->id,
            'role' => $this->role,
        ]);

        $query->andFilterWhere(['like', 'username', $this->username])
            ->andFilterWhere(['like', 'authKey', $this->authKey])
            ->andFilterWhere(['like', 'password', $this->password])
            ->andFilterWhere(['like', 'email', $this->email])
            ->andFilterWhere(['like', 'accessToken', $this->accessToken])
            ->andFilterWhere(['like', 'buscd', $this->buscd]);

        return $dataProvider;
    }
}

controllers/UsersController.php
<?php

namespace app\controllers;

use Yii;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Users;

class UsersController extends \yii\web\Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
//        print_r(Yii::$app->user->identity->username);exit;
        $this->layout = "@app/views/layouts/main-adm";
        return $this->render('index');
    }

    public function actionCreate()
    {
        // var_dump($_POST);exit();
        $model = new Users();
        if ($model->load(Yii::$app->request->post())) {
                $model->username = $_POST['Users']['username'];
                $model->password = sha1($_POST['Users']['password']);
                $model->email = $_POST['Users']['email'];
                $model->role = $_POST['Users']['role'];
                $model->created_at = date('Y-m-d H:i:s');
                if ($model->save()) {
                    $hasil = array(
                        'status' => "success",
                        'header' => "Berhasil",
                        'message' => "Users Berhasil Di Tambahkan !",
                    );
                    echo json_encode($hasil);
                    die();
                }
        }

        return $this->renderPartial('create', [
            'model' => $model,
        ]);
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post())) {
            $model->username = $_POST['Users']['username'];
            $model->password = sha1($_POST['Users']['password']);
            $model->email = $_POST['Users']['email'];
            $model->role = $_POST['Users']['role'];
            $model->updated_at = date('Y-m-d H:i:s');
            if ($model->save()) {
                $hasil = array(
                    'status' => "success",
                    'header' => "Berhasil",
                    'message' => "Users Berhasil Di Update !",
                );
                echo json_encode($hasil);
                die();
            }
        }

        return $this->renderPartial('update', [
            'model' => $model,
            'id' => $id,
        ]);
    }

    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        $hasil = array(
            'status' => "success",
            'header' => "Berhasil",
            'message' => "Users Berhasil Di Hapus !",
        );
        echo json_encode($hasil);
        die();
        // return $this->redirect(['adm/artikel']);
    }

    public function actionGetdatausers()
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;

        $data = Users::find()->asArray()->all();

        $row = array();
        $i = 0;
        foreach ($data as $idx => $value) {
            //Asiign All Value To Row
            foreach ($value as $key => $val) {
                $row[$i][$key] = $val;
            }
            $row[$i]['username'] = $value['username'];
            $row[$i]['email'] = $value['email'];
            $row[$i]['role'] = $value['role'];
            $row[$i]['fungsi'] = "
                <button onclick='updateusers(\"" . $value['id'] . "\")' type='button' rel='tooltip' data-toggle='tooltip' title='Edit Users' class='btn btn-sm btn-warning'><i class='fa fa-edit'></i></button>
                <button onclick='deleteusers(\"" . $value['id'] . "\")' type='button' rel='tooltip' data-toggle='tooltip' title='Hapus Users' class='btn btn-sm btn-danger'><i class='fa fa-trash'></i></button>
            ";
            $i++;
        }
        $hasil['data'] = $row;
            // var_dump($hasil);exit();
        return $hasil;
    }

    protected function findModel($id)
    {
        if (($model = Users::findOne($id)) !== null) {
            return $model;
        }
        throw new NotFoundHttpException('The requested page does not exist.');
    }


}

views/users/_form.php
<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Menu */
/* @var $form yii\widgets\ActiveForm */
?>
<style type="text/css">
    .geserkanan {
        margin-right: 5px;
    }
</style>
<div class="box box-primary">
    <div class="box-body">
        <div class="artikel-form">

            <?php $form = ActiveForm::begin([
                'fieldConfig' => [
                    'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
                    'horizontalCssClasses' => [
                        'label' => 'col-sm-4',
                        'wrapper' => 'col-sm-7',
                        // 'label' => 'col-md-4 col-sm-4 col-xs-12',
                        // 'wrapper' => 'col-md-6 col-sm-6 col-xs-12',
                    ],
                ],
                "options" => [
                    "id" => "form-users",
                    "class" => "",
                    "data-parsley-validate" => "",
                    'onsubmit'=>'return false;',
                    'enctype'=>'multipart/form-data',
                    'novalidate' => 'novalidate'
                ]
            ]); ?>
            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <?= $form->field($model, 'username')->textInput(['maxlength' => true, 'class' => 'form-control']) ?>
                            </div>
                            <div class="form-group">
                                <?= $form->field($model, 'password')->passwordInput(['maxlength' => true, 'class' => 'form-control']) ?>
                            </div>

                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <?= $form->field($model, 'email')->textInput(['maxlength' => true, 'type' => 'email', 'class' => 'form-control']) ?>
                            </div>

                            <div class="form-group">
                                <?=
                                $form->field($model, 'role')->dropDownList(
                                    ['' => 'Pilih Role...', '1' => '1', '2' => '2', '3' => '3'],
                                    ['class' => 'form-control validate[required]', 'id' => 'id_role']
                                );
                                    ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?php /* <div class="row">
                <div class="col-md-12">
                    <div class="form-group required">
                                <label class="control-label" for="first-name">File Items</label>
                                <!-- <div> -->
                                    <div class="file-loading">
                                        <input type="file" class="form-control" name="file_items" id="file_items" accept="image/*" required/>
                                    </div>
                                <!-- </div> -->
                    </div>
                </div>
            </div> */ ?>

            <div class="row">
                <div class="col-md-12">
                    <?= Html::a($model->isNewRecord ? '<i class="fa fa-floppy-o" aria-hidden="true"></i> Create' : '<i class="fa fa-pencil" aria-hidden="true"></i> Update', $model->isNewRecord ? 'javascript:saveusers()' : 'javascript:saveupdusers("' . $id . '")', ['class' => $model->isNewRecord ? 'btn btn-success pull-right' : 'btn btn-success pull-right']) ?>
                    <!-- <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button> -->
                    <?= Html::button('<i class="fa fa-times" aria-hidden="true"></i> Close', ['class' => 'btn btn-danger pull-right geserkanan', 'data-dismiss' => 'modal']) ?>
                </div>
            </div>
            <?php ActiveForm::end(); ?>

        </div>
    </div>
</div>
<script type="text/javascript">
    function saveusers() {
        {
            swal({
                title: "Konfirmasi",
                text: "Tambah Users ini?",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            }).then((ya) => {
                if (ya) {
                    var _data = new FormData($("#form-users")[0]);
                    $.ajax({
                        type: "POST",
                        data: _data,
                        dataType: "json",
                        contentType: false,
                        processData: false,
                        url: "<?=\Yii::$app->getUrlManager()->createUrl(['users/create'])?>",
                        beforeSend: function () {
                            swal({
                                title: 'Harap Tunggu',
                                text: "Memasukan Users Baru",
                                icon: 'info',
                                buttons: {
                                    cancel: false,
                                    confirm: false,
                                },
                                closeOnClickOutside: false,
                                onOpen: function () {
                                    swal.showLoading()
                                },
                                closeOnEsc: false,
                            });
                        },
                        complete: function () {
                            swal.close()
                        },
                        success: function (result) {

                            swal(result.header, result.message, result.status);

                            if (result.status == "success") {
                                window.location = "<?=\Yii::$app->getUrlManager()->createUrl(['users'])?>";
                            }
                        },
                        error: function (xhr, ajaxOptions, thrownError) {
                            swal("Error!", "Terdapat Kesalahan saat memasukan Users!", "error");
                        }
                    });
                } else {
                    // swal("Informasi", "Dokumen Tidak Dihapus", "info");
                }
            });
        }
    }

    function saveupdusers(id) {
        {
            swal({
                title: "Konfirmasi",
                text: "Ubah Users ini?",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            }).then((ya) => {
                if (ya) {
                    var _data = new FormData($("#form-users")[0]);
                    $.ajax({
                        type: "POST",
                        data: _data,
                        dataType: "json",
                        contentType: false,
                        processData: false,
                        url: "<?=\Yii::$app->getUrlManager()->createUrl(['users/update'])?>?id=" + id,
                        beforeSend: function () {
                            swal({
                                title: 'Harap Tunggu',
                                text: "Mengubah Users Baru",
                                icon: 'info',
                                buttons: {
                                    cancel: false,
                                    confirm: false,
                                },
                                closeOnClickOutside: false,
                                onOpen: function () {
                                    swal.showLoading()
                                },
                                closeOnEsc: false,
                            });
                        },
                        complete: function () {
                            swal.close()
                        },
                        success: function (result) {

                            swal(result.header, result.message, result.status);

                            if (result.status == "success") {
                                window.location = "<?=\Yii::$app->getUrlManager()->createUrl(['users'])?>";
                            }
                        },
                        error: function (xhr, ajaxOptions, thrownError) {
                            swal("Error!", "Terdapat Kesalahan saat memasukan Users!", "error");
                        }
                    });
                } else {
                    // swal("Informasi", "Dokumen Tidak Dihapus", "info");
                }
            });
        }
    }
</script>

views/users/create.php
<?php


/* @var $this yii\web\View */
/* @var $model app\models\Users */

?>
<div class="users-create">

    <?= $this->render('_form', [
        'model' => $model
    ]) ?>

</div>

views/users/index.php
<?php
/**
 * Created by PhpStorm.
 * Project : tiketing
 * User: fahmihilmansyah
 * Date: 2018-12-18
 * Email : fahmi.hilmansyah@gmail.com
 * Telp : 0817170820
 * Time: 00:09
 * Dilarang Keras Mengubah atau Mendistribusikan ulang code ini tanpa sepengetahuan.
 */
 ?>
 <?php

 use yii\bootstrap\ActiveForm;
 use yii\helpers\Html;

 // use fedemotta\datatables\DataTables;

 /* @var $this yii\web\View */
 /* @var $searchModel app\models\PAsetKategoriSearch */
 /* @var $dataProvider yii\data\ActiveDataProvider */

 $this->title = 'Users';
 $this->params['breadcrumbs'][] = $this->title;
 ?>
 <style type="text/css">
     .mright {
         margin-right: 5px;
     }

     #filternya {
         margin-left: 20%;
         width: 70%;
         position: absolute;
         z-index: 10;
     }
    /* .modal-lg {
        max-width: 60%;
    } */
 </style>
 <div class="menuusers-index">

     <h1 class="title"><?= Html::encode($this->title) ?></h1>

     <!-- <p class="pull-right"> -->
     <div class="row">
         <div class="col-md-12" align="right" style="margin-bottom:5px;">
             <?= Html::a('<i class="fa fa-plus"></i> Buat Users', 'javascript:addusers()', ['class' => 'btn btn-success']) ?>
         </div>
     </div>

     <?php
     $form = ActiveForm::begin([
         "options" => [
             "class" => "",
             // "id"    => "form-filter-juskeb",
             // 'onsubmit'=>'return true;',
         ]
     ]);
     ?>
    <div class="card">
       <!-- /.card-header -->
       <div class="card-body">
         <table id="tbl_users" class="table table-bordered table-striped">
                 <thead>
                 <tr>
                     <!-- <th style="width:5px;">No.</th> -->
                     <th>Username</th>
                     <th>Email</th>
                     <!-- <th>Deskripsi</th> -->
                     <th>Role</th>
                     <th style="width:100px;">Action</th>
                 </tr>
                 </thead>
             </table>

         </div>
    </div>
     <?php ActiveForm::end(); ?>
 </div>

 <div id="modalUsers" class="modal fade bs-example-modal" role="dialog" aria-hidden="true">
     <div class="modal-dialog modal-lg">
         <div class="modal-content">
             <div class="modal-header">
                 <!-- <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span></button> -->
                 <h4 class="modal-title" id="modalTitleUsers"></h4>
             </div>
             <div class="modal-body" id="modalBodyUsers">
                 Loading ...
             </div>
             <!-- <div class="modal-footer">
               <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
               <button type="button" class="btn btn-primary" id="modalBtnSave">Save changes</button>
             </div> -->
         </div>
     </div>
 </div>

 <script type="text/javascript">
     // var t = null;
     $(document).ready(function () {
         // t.destroy();

         $('#tbl_users').DataTable({
        //      "processing": true,
        // "serverSide": true,
             "ajax": '<?php echo \Yii::$app->getUrlManager()->createUrl("users/getdatausers");?>',
             "columns": [
                 {"data": "username"},
                 {"data": "email"},
                 // {"data": "desc"},
                 {"data": "role"},
                 {
                     "orderable": false,
                     "data": 'fungsi',
                     "defaultContent": ''
                 },

             ],
             "order": [[1, 'asc']]
         });
     });

     function addusers() {
         var url = "<?php echo \Yii::$app->getUrlManager()->createUrl(['users/create']);?>";
         var title = "Buat Users";
         showModal(url, title);
     }

     function updateusers(id) {
         var url = "<?php echo \Yii::$app->getUrlManager()->createUrl(['users/update']);?>?id=" + id;
         var title = "Update Users";
         showModal(url, title);
     }

     function showModal(url, title) {
         $("#modalTitleUsers").empty();
         $("#modalTitleUsers").html(title);

         $("#modalBodyUsers").empty();
         $("#modalBodyUsers").html("Loading ...");
         $("#modalBodyUsers").load(url);

         $('#modalUsers').modal({backdrop: 'static', keyboard: false});
         $("#modalUsers").modal("show");
         return false;
     }

     function deleteusers(id) {
         {
             swal({
                 title: "Konfirmasi",
                 text: "Hapus Users ini?",
                 icon: "warning",
                 buttons: true,
                 dangerMode: true,
             }).then((ya) => {
                 if (ya) {
                     $.ajax({
                         type: "GET",
                         // data: {id:id},
                         dataType: "json",
                         contentType: false,
                         processData: false,
                         url: "<?=\Yii::$app->getUrlManager()->createUrl(['users/delete'])?>?id=" + id,
                         beforeSend: function () {
                             swal({
                                 title: 'Harap Tunggu',
                                 text: "Sedang Menghapus Users",
                                 icon: 'info',
                                 buttons: {
                                     cancel: false,
                                     confirm: false,
                                 },
                                 closeOnClickOutside: false,
                                 onOpen: function () {
                                     swal.showLoading()
                                 },
                                 closeOnEsc: false,
                             });
                         },
                         complete: function () {
                             swal.close()
                         },
                         success: function (result) {

                             swal(result.header, result.message, result.status);

                             if (result.status == "success") {
                                 window.location = "<?=\Yii::$app->getUrlManager()->createUrl(['users'])?>";
                             }
                         },
                         error: function (xhr, ajaxOptions, thrownError) {
                             swal("Error!", "Terdapat Kesalahan saat menghapus Menu!", "error");
                         }
                     });
                 } else {

                 }
             });
         }

     }
 </script>

views/users/update.php
<?php


/* @var $this yii\web\View */
/* @var $model app\models\Users */

?>
<div class="users-update">

    <?= $this->render('_form', [
        'model' => $model,
        'id' => $id
    ]) ?>

</div>